'use strict';
const Sequelize = require('sequelize');

const {
  Model
} = require('sequelize');

module.exports = (sequelize) => {
  class User extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
	  User.hasMany(models.Course, {
			as: 'user',
			foreignKey: {
				fieldName: 'userId',
				allowNull: 'false'
			},
		})
    }
  };
  User.init({
    id: {type: Sequelize.INTEGER, primaryKey: true, autoGenerated: true},
    firstName: {type: Sequelize.STRING, allowNull: false},
    lastName: {type: Sequelize.STRING, allowNull: false},
    emailAddress: {type: Sequelize.STRING, allowNull: false, validate: {
      // 'validate isEmail' validator referenced from
	  // https://sequelize.org/master/manual/validations-and-constraints.html
	  isEmail: {
        msg: 'Please enter a valid email address'
      }
    }},
    password: {type: Sequelize.STRING, allowNull: false}
  }, {
    sequelize,
    modelName: 'User',
  });  
  return User;
};